import { useState, useEffect, useRef } from "react";
import { MessageSquare, X, Send, Bot, User } from "lucide-react";
import { v4 as uuidv4 } from "uuid";
import { GoogleGenAI } from "@google/genai";

interface Message {
  id: string;
  role: "user" | "model";
  content: string;
}

export default function Chatbot() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      role: "model",
      content:
        "Hi there! I'm the Proven Media Team AI assistant. How can I help you scale your business today?",
    },
  ]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [sessionId] = useState(() => uuidv4());
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim()) return;

    const userMsg: Message = { id: uuidv4(), role: "user", content: input };
    const newMessages = [...messages, userMsg];
    setMessages(newMessages);
    setInput("");
    setIsLoading(true);

    try {
      const ai = new GoogleGenAI({ apiKey: import.meta.env.VITE_GEMINI_API_KEY || process.env.GEMINI_API_KEY });
      
      const systemInstruction = `
        You are an AI Sales Assistant for Proven Media Team, a performance-driven media and automation agency.
        Your goal is to qualify leads and guide them to book a strategy call.
        
        Rules:
        - Identify intent within first 2-3 turns.
        - Ask one question at a time.
        - Match user tone.
        - Guide toward ONE primary action: Book a Strategy Call.
        - Never oversell.
        - Never fabricate pricing or policies.
        - Use only verified business data.

        Services: Social media management, Short-form and long-form video production, Meta Ads management, SEO & hashtag optimization, Google Business Profile setup & optimization, AI Landing Pages, AI Chatbot integration, AI Voice Agent setup, Funnel builds, CRM integration, Strategy audits, KPI dashboards.
        
        Pricing Tiers:
        - Basic: $595/mo (1 platform, 12 posts, 2 reels, basic editing/engagement/SEO, monthly call/report, GBP setup)
        - Premium: $795/mo (2-3 platforms, 20-24 posts, 2-4 reels, 1-2 long-form, advanced editing/research, Meta Ads management, KPI snapshots, quarterly planning)
        - Elite: Starting at $1,495/mo (3-4 platforms, 30+ posts, 5 reels, 2-4 long-form, motion graphics, full outreach, AI Landing Page/Chatbot/Voice Agent included, full funnel, CRM, custom dashboard)
        
        Add-ons: 4 Reels ($395), 8 Reels ($795), 12 Reels ($1,295), AI Landing Page ($800-$1,200 setup), AI Voice Agent ($250-$400 setup + $65-$125/mo), GBP Setup ($150), GBP Ongoing ($90/mo), Meta Ads Setup ($200), Meta Ads Management ($500-$1,500/mo), Advanced Strategy Audit ($500), Weekly KPI Dashboard ($150/mo).

        If unsure of pricing or scope, say: "Let me confirm that for you."
        
        Lead Qualification Flow:
        1. Business type
        2. Primary goal
        3. Current marketing stage
        4. Budget range
        5. Timeline
        
        If qualified, offer booking link: /book
        If not qualified, offer resources: /resources
      `;

      const contents = newMessages.map((msg) => ({
        role: msg.role === "user" ? "user" : "model",
        parts: [{ text: msg.content }],
      }));

      // We skip the very first welcome message as it wasn't generated by the model in this session
      const apiContents = contents.slice(1);
      if (apiContents.length === 0) {
        apiContents.push(contents[0]);
      }

      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: apiContents,
        config: {
          systemInstruction,
        },
      });

      const reply = response.text || "I'm sorry, I couldn't process that.";

      setMessages((prev) => [
        ...prev,
        { id: uuidv4(), role: "model", content: reply },
      ]);
      
      // Optionally, we could still log the chat to the backend here asynchronously
      fetch("/api/chat/log", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sessionId, userMessage: userMsg.content, modelReply: reply }),
      }).catch(console.error);

    } catch (error) {
      console.error("Chat error:", error);
      setMessages((prev) => [
        ...prev,
        {
          id: uuidv4(),
          role: "model",
          content:
            "Sorry, I'm having trouble connecting right now. Please try again later or book a call directly.",
        },
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed bottom-6 right-6 z-50">
      {/* Chat Button */}
      {!isOpen && (
        <button
          onClick={() => setIsOpen(true)}
          className="bg-accent1 text-primary p-4 rounded-full shadow-2xl hover:bg-accent1-hover transition-transform hover:scale-105 flex items-center justify-center"
        >
          <MessageSquare size={24} />
        </button>
      )}

      {/* Chat Window */}
      {isOpen && (
        <div className="bg-primary w-[350px] sm:w-[400px] h-[500px] rounded-2xl shadow-2xl flex flex-col border border-neutral-700 overflow-hidden animate-in slide-in-from-bottom-4 duration-300">
          {/* Header */}
          <div className="bg-primary-hover text-white p-4 flex justify-between items-center border-b border-neutral-700">
            <div className="flex items-center gap-2">
              <Bot size={20} />
              <span className="font-semibold">Sales Assistant</span>
            </div>
            <button
              onClick={() => setIsOpen(false)}
              className="text-neutral-400 hover:text-white transition-colors"
            >
              <X size={20} />
            </button>
          </div>

          {/* Messages */}
          <div className="flex-grow p-4 overflow-y-auto bg-primary flex flex-col gap-4">
            {messages.map((msg) => (
              <div
                key={msg.id}
                className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
              >
                <div
                  className={`max-w-[80%] p-3 rounded-2xl text-sm ${
                    msg.role === "user"
                      ? "bg-accent1 text-primary rounded-tr-sm"
                      : "bg-primary-hover border border-neutral-700 text-white rounded-tl-sm shadow-sm"
                  }`}
                >
                  {msg.content}
                </div>
              </div>
            ))}
            {isLoading && (
              <div className="flex justify-start">
                <div className="bg-primary-hover border border-neutral-700 p-3 rounded-2xl rounded-tl-sm shadow-sm flex gap-1">
                  <div className="w-2 h-2 bg-neutral-400 rounded-full animate-bounce" />
                  <div
                    className="w-2 h-2 bg-neutral-400 rounded-full animate-bounce"
                    style={{ animationDelay: "0.2s" }}
                  />
                  <div
                    className="w-2 h-2 bg-neutral-400 rounded-full animate-bounce"
                    style={{ animationDelay: "0.4s" }}
                  />
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          {/* Input */}
          <div className="p-4 bg-primary border-t border-neutral-700">
            <div className="flex items-center gap-2">
              <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleSend()}
                placeholder="Type your message..."
                className="flex-grow px-4 py-2 rounded-full border border-neutral-700 bg-primary-hover text-white focus:outline-none focus:border-accent1 focus:ring-1 focus:ring-accent1 text-sm"
              />
              <button
                onClick={handleSend}
                disabled={!input.trim() || isLoading}
                className="bg-accent1 text-primary p-2 rounded-full hover:bg-accent1-hover disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                <Send size={18} />
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
